version: '3.8'

services:
  # MySQL baza podataka
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-skladiste}
      MYSQL_USER: ${MYSQL_USER:-skladiste_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-skladiste_pass}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - skladiste-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - skladiste-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # FastAPI aplikacija
  app:
    build: .
    ports:
      - "80:8000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER:-skladiste_user}:${MYSQL_PASSWORD:-skladiste_pass}@mysql:3306/${MYSQL_DATABASE:-skladiste}
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
    networks:
      - skladiste-network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  skladiste-network:
    driver: bridge 